import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";

export default function home(props) {
  const router = useRouter();

  setTimeout(function () {
    router.back();
  }, 3000);
  return (
    <>
      <Head>
        <title>Bevestiging | Castaar Inventaris</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main main-overview">
        <p>
          Dit is een bevestiging dat alles correct verlopen is, je wordt
          automatisch teruggestuurd.
        </p>
      </main>
    </>
  );
}
