import React from "react";
import Head from "next/head";

import InfoBlock from "../components/blocks/info-block";

export default function home() {
  return (
    <>
      <Head>
        <title>Home | Castaar Inventaris</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main main-overview">
        <InfoBlock value={"€ xx"} title={"Waarde totale stock"} />
        <InfoBlock value={"XX M2"} title={"Borden"} />
      </main>
    </>
  );
}
